<?php
$typeArr[1] = '商业观点';
$typeArr[2] = '金融创投';
$typeArr[3] = '商业立场';
$typeArr[4] = '人物访谈';
$typeArr[5] = '营销';
$typeArr[6] = '分享';
$typeArr[7] = '互联天下';
$typeArr[9] = '业界';
$typeArr[10] = '关于我们';
$typeArr[11] = '电商';
$typeArr[12] = '传媒';
$typeArr[13] = '通信';
$typeArr[14] = '创业';
$typeArr[15] = '人物';
$typeArr[16] = '金融';
$typeArr[17] = '投资';
$typeArr[18] = '商投';
$typeArr[19] = '案例';
$typeArr[20] = '移动';
$typeArr[21] = '金融';
$typeArr[22] = '手游';
$typeArr[23] = '关于我们';
$typeArr[24] = '寻求报道';
$typeArr[25] = '商务合作';
$typeArr[26] = '版权申明';
$typeArr[27] = '联系我们';
?>