<?php
$z[0]=Array("sppage","",0,59);
$z[0][4]['sptype']="full";
$z[0][4]['srul']="1";
$z[0][4]['erul']="5";
$z[1]=Array("previewurl","http://www.tmtpost.com/108339.html",61,130);
$z[2]=Array("keywordtrim","",132,169);
$z[3]=Array("descriptiontrim","<p class=\"post_content\">[ÄÚÈÝ]</p></div> \r\n		<div class=\"post-txt\" id=\"post-txt\">\r\n",171,299);
$z[4]=Array("item","\r\n   {dede:match}<h2>[ÄÚÈÝ]</h2>{/dede:match}\r\n   \r\n   {dede:function}{/dede:function}\r\n",301,455);
$z[4][4]['field']="title";
$z[4][4]['value']="";
$z[4][4]['isunit']="";
$z[4][4]['isdown']="";
$z[5]=Array("item","\r\n   {dede:match}{/dede:match}\r\n   \r\n   {dede:function}{/dede:function}\r\n",455,595);
$z[5][4]['field']="writer";
$z[5][4]['value']="";
$z[5][4]['isunit']="";
$z[5][4]['isdown']="";
$z[6]=Array("item","\r\n   {dede:match}{/dede:match}\r\n   \r\n   {dede:function}{/dede:function}\r\n",595,735);
$z[6][4]['field']="source";
$z[6][4]['value']="";
$z[6][4]['isunit']="";
$z[6][4]['isdown']="";
$z[7]=Array("item","\r\n   {dede:match}{/dede:match}\r\n   \r\n   {dede:function}{/dede:function}\r\n",735,876);
$z[7][4]['field']="pubdate";
$z[7][4]['value']="";
$z[7][4]['isunit']="";
$z[7][4]['isdown']="";
$z[8]=Array("item","\r\n   {dede:match}<div class=\"post-txt\" id=\"post-txt\">[ÄÚÈÝ]<div class=\"post-classify\">{/dede:match}\r\n   \r\n   {dede:function}{/dede:function}\r\n",876,1085);
$z[8][4]['field']="body";
$z[8][4]['value']="";
$z[8][4]['isunit']="1";
$z[8][4]['isdown']="1";

?>