<li>
<div class="viewimg"><div class="hotimgzz"></div><a href="[field:arcurl/]" class="zzsz">
</a><a href="[field:arcurl/]" target="_blank" title="[field:title/]">
<img src="[field:litpic/]" alt="[field:title/]" width="250" height="165">
</a>
<div class="standpoint">[field:typename/]</div>
</div>
<h3><a href="[field:arcurl/]">[field:title/]</a></h3>
<p>[field:description/]...</p>
<span>×÷Õß£º[field:writer /] [field:pubdate function="GetDateTimeMK(@me)"/]</span> 
</li>