<?php
$z[0]=Array("field","三星,移动支付",0,54);
$z[0][4]['name']="keywords";
$z[1]=Array("field","三星强调这不仅是关于移动支付，而是打造一款用途更广泛的移动钱包，而且几乎无需要求商家或消费者改变习惯。",56,202);
$z[1][4]['name']="description";
$z[2]=Array("field","三星收购苹果支付对手LoopPay，致力打造全面型移动钱包",204,293);
$z[2][4]['name']="title";
$z[3]=Array("field","",295,334);
$z[3][4]['name']="writer";
$z[4]=Array("field","",336,375);
$z[4][4]['name']="source";
$z[5]=Array("field","",377,417);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","<p></p>\n<p>【钛媒编译】<span class='wp_keywordlink_affiliate'></span>今天宣布收购网络支付公司LoopPay，将致力于把其技术应用到将来的设备中。</p>\n<p>三星强调这不仅是关于<span class='wp_keywordlink_affiliate'></span>，而是打造一款用途更广泛的移动钱包，而且几乎无需要求商家或消费者改变习惯。</p>\n<p>“LoopPay技术令人兴奋因为其覆盖面广。”三星创新中心的Injong Rhee博士说。他表示磁安全传输(MST)技术能在目前美国商店中约90%的支付终端机上使用。“如果你去看其他移动支付方案（包括苹果支付），它们实际上都基于近场技术，而这种技术在美国应用很有限。LoopPay拥有的MST技术有巨大潜能去解决终端用户的覆盖问题。”</p>\n<p>LoopPay公司的CEO Will Graylin称2013年11月LoopPay在众筹网站Kickstarter发起了一个项目，不久就和三星签订了合同。</p>\n<p>“这肯定是一个长期的合作，”Graylin说，“实际上在2014年7月我们和Visa、Synchrony Financial一起进行了合作。我们并没有宣布该项投资，因此我们之前的关系要比公众猜想的长”。</p>\n<p><span style=\"line-height: 1.5;\">(文章编译自,)</span></p>",419,1404);
$z[6][4]['name']="body";
$z[7]=Array("field","/uploads/allimg/c150303/14253Z91YZ-5bO.jpg",1406,1487);
$z[7][4]['name']="litpic";

?>