<li class="first-news">
<div class="inner-content">
<div class="post-thumbnail">
<a href="[field:arcurl/]" title="[field:title/]" target="_blank">			
<img src="[field:litpic/]" alt="[field:title/]">
<span class="overlay-icon"></span>
</a></div>					
<h2><a href="[field:arcurl/]" title="[field:title/]" target="_blank">[field:title/]</a></h2>
<p class="post-meta">
[field:pubdate function="MyDate('Y年m月d日',@me)"/] 
<a href="[field:arcurl/]" title="[field:title/]"></a>		查看：	[field:click/] 			</p>
<div class="entry">[field:infos/] ...	
<a class="more-link" href="[field:arcurl/]" target="_blank">阅读更多 ?</a>
</div>
</div>
</li>