<?php
$z[0]=Array("arcurl","",93,108);
$z[1]=Array("title","",117,131);
$z[2]=Array("litpic","",164,179);
$z[3]=Array("title","",186,200);
$z[4]=Array("arcurl","",270,285);
$z[5]=Array("title","",294,308);
$z[6]=Array("title","",326,340);
$z[7]=Array("pubdate","",374,425);
$z[7][4]['function']="MyDate('YÄêmÔÂdÈÕ',@me)";
$z[8]=Array("arcurl","",437,452);
$z[9]=Array("title","",461,475);
$z[10]=Array("click","",490,504);
$z[11]=Array("infos","",533,547);
$z[12]=Array("arcurl","",581,596);

?>