{dede:field name='keywords'}TMT行业观点平台,科技媒体,互联{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}收购Skybox，Google今后如何放卫星？{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='body'}<p>
				<p><img class="aligncenter size-full wp-image-115967" title="谷歌" src="/uploads/allimg/c140614/1402H2QQP-24027.jpg" alt="谷歌" width="550" height="310" /></p>
<p>就在阿里巴巴收购UC的同一天，Google宣布收购卫星公司SkyboxImaging，但这个收购明显被阿里的“光环”遮住了。但相对于阿里上市前的圈地，Google的这次收购，则会对未来人类生产生活产生重大影响。</p>
<p>&nbsp;</p>
<p><strong>SkyboxImaging不是一般的卫星公司</strong></p>
<p>卫星产业长期以来都以发射多任务的“大卫星”为主，由于投资成本高、研发周期长，导致卫星的单价非常高，而且因为技术集成难度大，故障发生的频率也很高。随着业界对卫星需求的持续增加，质量小、技术简单、研发周期短、成本低的小卫星越来越受欢迎。这些小卫星可能只有单一的功能，但由于研发速度快，能够快速交付使用，并且故障率也很低。目前在通信、对地观测、空间遥感、气象观测等方面有着很大的应用。</p>
<p>SkyboxImaging这家公司就是以研发小卫星起家的公司，成立于2009年。在小卫星行业里，SkyboxImaging有着独特的竞争优势。首先，SkyboxImaging是业界第一家可以独立拍摄地球高清视频的卫星公司，其他竞争者充其量只能拍摄高清图片，像PlanetLab的卫星比Skybox小很多，发射升空之后能做的事情也很少，而Urthecast的产品虽然可以拍摄地球视频，但它自己本身没有研发卫星，它是依靠架设在在国际太空站上摄像头拍摄。</p>
<p>在小卫星行业，大多数公司都是通过卖采集来的的信息赚钱。我们都知道卫星捕捉到的不过是一幅幅的图片，这些图片数据本身并无价值，卫星公司需要利用算法的进行甄别、归类形成有价值的信息，然后出售。但Skybox并不是以算法著称的公司，他们真正的竞争力是什么？数据平台！</p>
<p>在过去的几年里，他们收集到海量的地球数据，这些数据不仅来自于自己的卫星，还有很多公共卫星数据，比如全球各地的历史天气数据。这些海量数据构成一个平台，类似于亚马逊的AWS，在AWS上，全球各地的创业者只需一张信用卡就可以调取来自亚马逊的海量数据、工具，从而开创自己的<span class='wp_keywordlink_affiliate'><a href="http://www.tmtpost.com/tag/web" title="查看 互联网 中的全部文章" target="_blank">互联网</a></span>公司，instagram、quora就是成功的案例。而如果你不是要做互联网创业，你要线下创业，你要开设工厂、你要做农业，Skybox的海量数据就成为你线下的AWS，在Skybox的平台，开发者的工具可以随时调用，模块化的设计理念践行了云的理念。</p>
<p>现在，Google买下了Skybox。</p>
<p>&nbsp;</p>
<p><strong>Google用卫星能做什么？</strong></p>
<p>一个显而易见的事实是，Skybox会成为Google改善地图和Googleearth精确度的重要武器，这两个产品对于Google的重要性不言而喻，我曾说过，Google无人驾驶汽车的精髓是在Google地图，软件（服务）的力量已然超越硬件（汽车本身）。同时，Google地图也是Google移动化布局的重要棋子，Google押注的移动智能助理GoogleNow也是基于位置的应用，这一切都离不开精确的地图定位和导航。</p>
<p>GoogleX实验室一直在研发热气球搭载WIFI的“ProjectLoon”项目，买下Skybox后，这个项目会借助卫星而快速部署，毕竟发射卫星比发射热气球的技术要成熟很多。Google的“ProjectLoon”项目名义上是为了解决偏远地区的上网问题，实际上还是一种上网入口之争，但至少客观上已经为当地人谋了些福利。</p>
<p>第三，Google要造另一朵“云”，以对抗亚马逊的AWS。众所周知，亚马逊的AWS早已称霸云计算领域，无论是Google还是微软，短期内都无法赶超（长期看也很悲观，更别提国内的所谓云计算公司了）。借助Skybox，Google有望造一朵新“云”，如前文所言，skybox上拥有着关于地球的海量信息，这些来自原子世界的信息是Google、亚马逊之类的互联网企业所欠缺的，Google已完成对比特世界信息的搜集，如今，Google将迎来对原子世界信息的整合。当原子信息和比特信息相互碰撞、融合、重组，Google会实现“整合全球信息”的愿景，在此基础上，大量开发者可以充分利用这些数据开发出面向物理世界的工具、产品，为那些线下的创业者——制造业、农业、运输业的从业者带来巨大革新！</p>
<p>我曾不止一次的说过，Google会从比特世界走入原子世界。<strong>Google眼镜、Google无人驾驶汽车以及未来的Google卫星，这些看似无关的产品和布局其实都在践行Google“一切以信息为主”的理念。</strong>赚钱，当然是每个公司尤其是上市公司的天职，但是不是要改变世界，却彰显出不同公司之间的价值观，这一点中国公司还差得很远。</p>
<p>&nbsp;</p>
			
				<p></><span>（关注更多<a href="http://www.tmtpost.com/">钛媒体</a>作者观点，参与钛媒体微信互动（微信搜索“钛媒体”或“taimeiti”））</span></p>
			</p>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c140614/1402H2QQP-24027_lit.jpg{/dede:field}
