<?php
$z[0]=Array("field","APP,智能终端,硅谷新公司",0,64);
$z[0][4]['name']="keywords";
$z[1]=Array("field","PhotoMath是硅谷的又一个奇迹——上线仅24小时之后，它就荣登了App Store的榜首，并且在Disrupt London的活动上，随处可以听到人们在谈论它。",66,242);
$z[1][4]['name']="description";
$z[2]=Array("field","【硅谷新公司】最叫座App PhotoMath：用摄像头算数学题",244,333);
$z[2][4]['name']="title";
$z[3]=Array("field","",335,374);
$z[3][4]['name']="writer";
$z[4]=Array("field","",376,415);
$z[4][4]['name']="source";
$z[5]=Array("field","",417,457);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","<p></p>\n<p style=\"text-align: left;\"><strong>】为特色栏目，连线记者站，每日速递，、新模式新动态）</strong></p>\n<p>PhotoMath是一款创新型App。你只需将自己手机的摄像头放置在数学等式上，就会自动得到结果，并且PhotoMath会告诉你解这道数学题的详细步骤。在iOS版本取得了巨大成功之后，这一App近日推出了Android版本。</p>\n<p>当记者在伦敦第一次把玩这款软件的时候，我被它的设计和整体用户体验震撼了。事实上，在计算机上解决一个数学问题已经不是什么新鲜事儿了——WolframAlpha已经做这件事很多年了。但是，在WolframAlpha内输入一个等式是一个痛苦的过程，但是有了PhotoMath，你只需对准、点击就可以轻松地得到结果。</p>\n<p>日前，在新推出的Android版本上，这一App可以支持计算二次等式、不等式等。新版本的App计算速度更快，并且在很大细节方面都作了改版。</p>\n<p>令我最没有想到的是人们对这一软件的热情。在它上线仅24小时之后，它就荣登了App Store的榜首，并且在Disrupt London的活动上，随处可以听到人们在谈论它。</p>\n<p>PhotoMath背后的初创公司是MicroBlink，这是一家文字识别科技公司。这家公司致力于最快最精准地进行文字扫描，而PhotoMath正是其实时文字识别引擎的最好的证明产品。</p>\n<p>目前，该App已经在iOS和Windows Phone领域拥有了1100万的下载量，人们疯狂地下载和使用着它。仅一月一个月，它被用来解决了800万道的数学问题。目前，这款软件开始支持Android版本。它仍是免费下载的，有望拥有很多手持廉价Android手机的高中生用户。<strong style=\"line-height: 1.5;\">（本栏目中的项目皆由搜集、整理）</strong></p>",459,1850);
$z[6][4]['name']="body";
$z[7]=Array("field","/uploads/allimg/c150303/14253ZP2030-236495.jpg",1852,1937);
$z[7][4]['name']="litpic";

?>