<article class="item-list">
		<h2><a href="[field:arcurl/]" title="[field:title/]">[field:title/]</a></h2>
		<p class="post-meta">
						[field:pubdate function="MyDate('Y年m月d日',@me)"/] 查看：[field:click/] 
								所属栏目：<a href="[field:typeurl/]" title="查看[field:typename/]的全部内容">[field:typename/]</a></p>							
		<div class="post-thumbnail">
			<a href="[field:arcurl/]" title="[field:title/]">
				<img width="150" height="75" src="[field:litpic/]" class="attachment-thumbnail" alt="[field:title/]">			</a>
		</div>
					<div class="entry">
			<p>[field:infos/]... 			<a class="more-link" href="[field:arcurl/]">阅读更多 ?</a></p>
		</div>					
	</article>