{dede:field name='keywords'}Paypal,并购,移动支付{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}PayPal 2.8亿美元收购移动支付公司Paydiant以对抗苹果支付{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='body'}<p>&nbsp;</p>
<p><img class="aligncenter size-medium wp-image-199240" title="paypal" src="/uploads/allimg/c150303/14253Z063K0-11960.jpg" alt="" width="400" height="299" /></p>
<p>eBay的支付公司PayPal将要收购<span class='wp_keywordlink_affiliate'></span>创业公司Paydiant，后者能授权大零售商使用其技术平台创建它们自己的移动钱包应用。多个消息来源称收购价大约为2.8亿美元，收购有望在本月或下月完成。</p>
<p>Paydiant公司创建于2010年，位于美国麻省。它的平台被快餐连锁赛百味和其他零售商、银行使用为他们自己的应用增加支付、忠诚度和电子优惠券功能。也就是说，该公司是帮助其他公司打造自己的支付方式的。<strong>其支付技术包括二维码扫描和近场通信等非常适合商家的业务。</strong></p>
<p>该公司的客户还包括沃尔玛领导的仓储式商店联盟MCX，它会员包括Target、Best Buy和Kohl’s等大型零售连锁商，该联盟表示将在下半年推出自己的移动钱包应用CurrentC。</p>
<p><span style="line-height: 1.5;">在过去几年里，PayPal一直在寻找网络支付之外的新增长领域，试图成为实体店的流行支付方式，但至今并不成功。</span></p>
<p>然而当苹果、谷歌和三星都在携自己的移动支付系统激烈争夺店内购物体验之际，此次收购却让PayPal变成了零售商的盟友。许多零售商并不想被一家强势支付服务所支配，无论是苹果还是谷歌。最终，一些零售商会觉得与像PayPal这样的其他支付服务合作将对他们有利。</p>
<p>这项收购将让PayPal成为更多应用的支付方式，也让它在下半年准备脱离eBay独立上市之时有了新的故事可讲。</p>
<p>PayPal的商业业务主管Bill Ready表示，尽管有来自大公司的竞争，PayPal相信一些零售商将选择推出自己的移动钱包。</p>
<p>苹果公司在秋天推出了苹果支付，谷歌最近与无线运营商达成协议让谷歌钱包预装到数百万的智能手机里，而三星则刚宣布自己的支付系统三星支付。</p>
<p>“我不认为这是非此即彼的选择，”Ready说，“我们确定商家和大零售商想根据他们所接受的掌控自己的命运”。</p>
<p>去年零售商联盟的两家零售商CVS和Rite Aid在最初接受后关闭了对苹果支付的支持。它的一个主要目标是创建一个移动应用方便顾客支付，比如银行账户连接或店家购物卡，零售店处理起来更省钱。而苹果支付目前只支持传统的借记卡和信用卡，这增加了零售商的处理成本。</p>
<p><span style="line-height: 1.5;">Paydiant公司至今已经融资3500万美元，投资者包括General Catalyst、North Bridge Growth Equity &amp; Venture Partners和Stage 1 Ventures等多家风投公司。（本文首发<span class='wp_keywordlink'></span>）</span></p>
<p><span style="line-height: 1.5;">(来源VB, Re/code, </span><span style="line-height: 1.5;">; http://venturebeat.com/2015/03/02/paypal-acquires-mobile-payment-startup-paydiant/)</span></p>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c150303/14253Z063K0-11960_lit.jpg{/dede:field}
