<?php
$z[0]=Array("field","",147,175);
$z[0][4]['name']="typeurl";
$z[1]=Array("field","",177,206);
$z[1][4]['name']="typename";
$z[2]=Array("arclist","\r\n<div class=\"mega-menu-item \"> <a href=\"[field:arcurl/]\" title=\"[field:title/]\"> <img src=\"[field:litpic/]\" width=\"235\" height=\"117\"></a>\r\n<h3 class=\"post-box-title\"> <a class=\"mega-menu-link\" href=\"[field:arcurl/]\" title=\"[field:title/]\">[field:title/]</a> </h3>\r\n</div>\r\n",357,710);
$z[2][4]['orderby']="rand";
$z[2][4]['row']="3";
$z[2][4]['titlelen']="60";
$z[2][4]['type']="image";
$z[3]=Array("channel","\r\n<li class=\"menu-item  menu-item-type-taxonomy  menu-item-object-category\"> <a href=\"[field:typelink/]\">[field:typename/]</a></li>\r\n",795,981);
$z[3][4]['type']="son";
$z[3][4]['noself']="yes";

?>