<?php
$z[0]=Array("sppage","",0,59);
$z[0][4]['sptype']="full";
$z[0][4]['srul']="1";
$z[0][4]['erul']="5";
$z[1]=Array("previewurl","http://www.tmtpost.com/199091.html",61,130);
$z[2]=Array("keywordtrim","",132,169);
$z[3]=Array("descriptiontrim","<p class=\"post_content\">[ÄÚÈÝ]</p>\r\n		</div> \r\n		\r\n		<div class=\"post-txt\" id=\"post-txt\">\r\n",171,307);
$z[4]=Array("item","\r\n   {dede:match}<h1 class=\"tit\">[ÄÚÈÝ]</h1>{/dede:match}\r\n   \r\n   {dede:function}{/dede:function}\r\n",309,475);
$z[4][4]['field']="title";
$z[4][4]['value']="";
$z[4][4]['isunit']="";
$z[4][4]['isdown']="";
$z[5]=Array("item","\r\n   {dede:match}{/dede:match}\r\n   \r\n   {dede:function}{/dede:function}\r\n",475,615);
$z[5][4]['field']="writer";
$z[5][4]['value']="";
$z[5][4]['isunit']="";
$z[5][4]['isdown']="";
$z[6]=Array("item","\r\n   {dede:match}{/dede:match}\r\n   \r\n   {dede:function}{/dede:function}\r\n",615,755);
$z[6][4]['field']="source";
$z[6][4]['value']="";
$z[6][4]['isunit']="";
$z[6][4]['isdown']="";
$z[7]=Array("item","\r\n   {dede:match}{/dede:match}\r\n   \r\n   {dede:function}{/dede:function}\r\n",755,896);
$z[7][4]['field']="pubdate";
$z[7][4]['value']="";
$z[7][4]['isunit']="";
$z[7][4]['isdown']="";
$z[8]=Array("item","\r\n   {dede:match}<div class=\"paragraph\">[ÄÚÈÝ]<div class=\"paragraph\">{/dede:match}\r\n   {dede:trim replace=\"\"}<a([^>]*)>(.*)</a>{/dede:trim}\r\n   {dede:function}{/dede:function}\r\n",896,1140);
$z[8][4]['field']="body";
$z[8][4]['value']="";
$z[8][4]['isunit']="1";
$z[8][4]['isdown']="1";

?>