{dede:field name='keywords'}IBM,坏消息,聚美优品{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}柴静《穹顶之下》引来两个相关部门的三篇网文纠葛｜3月3日坏消息榜{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='body'}<p><img class="aligncenter size-full wp-image-199255" title="坏消息" src="/uploads/allimg/c150303/14253Z0Aa0-3ZW.jpg" alt="坏消息" width="600" height="305" /></p>
<p>关注<span class='wp_keywordlink'></span>每日、每月整理发布的行业<span class='wp_keywordlink_affiliate'></span>榜，一榜略尽当日当月最具影响的坏消息。</p>
<p>&nbsp;</p>
<p><strong>NO.1 </strong><span style="line-height: 1.5;">昨日，立方石油网登载来自微信朋友圈传播的文章《终于有中石油员工来和柴静谈谈石油的事》，作者据称为匿名中石油员工，从事环保工作。文章认为《穹顶之下》纪录片存在刻意导向、结论肤浅等问题，称全球石油行业垄断特性之下，</span></p>
<blockquote><p>“全面放开油气开采，任谁都能在中国找块地打几个眼，看看有没有石油天然气，那才真的是环境的灾难”。</p></blockquote>
<p>今天，中石油质量与标准管理部副总工程师万战翔也针对《穹顶之下》撰文发表意见，文章称</p>
<blockquote><p>“但她（柴静）真的不是内行专家，一知半解，尽情发挥。是属于“外行看热闹”、说热闹的”，“也许是她脑力不够，也许是她知识不够，也许是她思想不够，反正并无什么真知灼见”</p></blockquote>
<p>文章提出《穹顶之下》纪录片存在的问题，例如：谈雾霾原因不分主次轻重、不了解天然气开发技术、发改委不敢过问油品成本的说法属无稽之谈等等。</p>
<p>万战翔认为该纪录片“对错七三开”，出发点是好的，热心是好的，同时表示</p>
<blockquote><p>“一句话就可概括中国雾霾之殇：每个老百姓都是雾霾的制造者，但是，管控、治理、消除雾霾，责任在政府”。</p></blockquote>
<p>另外，环保部部长陈吉宁近日也对柴静发布的穹顶之下》表达了看法，陈吉宁称自己当天晚上就已完整看完，昨天上午还专门给柴静发短信感谢，感谢她唤起全民对环境问题的关注。</p>
<p>中石油万战翔的文章发布后，今日下午15点07分，环保部专家、环境科学研究院副研究员岳欣发布微博长文《致中石油高层万战翔有关对柴静“穹顶之下”的评论》，对万战翔所提出的5点视频中的错误一一回应，岳欣表示</p>
<blockquote><p>“请万秘书长仔细看完柴静的片子，再来说话”，“很多片中都有交代，您还在这说来说去，没有意义”。</p></blockquote>
<p>&nbsp;</p>
<p style="text-align: left;"><strong>今日坏消息榜单NO.2-NO.8</strong></p>
<p>&nbsp;</p>
<p><span style="line-height: 1.5;">NO.2 <strong>四川沱牌舍得酒业</strong>今日公告宣布股权转让及增资扩股事宜首次延期公告期满，尚未征集到意向受让方，其<strong>股权转让挂牌第二次流标</strong>。</span></p>
<p><span style="line-height: 1.5;">NO.3 </span><span style="line-height: 1.5;">近日一卡通公司推出<strong>网络充值便民服务，但充值后还需要购买一个名为&#8221;E乐充&#8221;的设备</strong>，将资金圈至一卡通内，不少市民认为一卡通公司<strong>捆绑收费</strong>，一卡通公司回应称读卡是从技术上设定的，有助于节省刷卡时间。</span></p>
<p><span style="line-height: 1.5;">NO.4 </span><strong style="line-height: 1.5;"></strong><span style="line-height: 1.5;"><strong><span class='wp_keywordlink_affiliate'></span>一名股东近日起诉该公司</strong>在将半导体业务出售给Global Foundries一事上涉嫌<strong>证券欺诈</strong>，根据起诉书显示，IBM在出售了其半导体业务之后夸大了其股票价格，IBM并未标记该业务为&#8221;亏本生意&#8221;。</span></p>
<p><span style="line-height: 1.5;">NO.5 今年</span><strong style="line-height: 1.5;">2月份澳门博彩业收入同比下滑49%</strong><span style="line-height: 1.5;">至195.4亿澳门元（约合24.5亿美元），创下有史以来最大降幅。这也是澳门博彩业收入连续第九个月下滑。</span></p>
<p><span style="line-height: 1.5;">NO.6 </span><strong style="line-height: 1.5;">恒大地产旗下的Golden Fast Foods Pty</strong><span style="line-height: 1.5;">于去年11月通过一系列空壳公司在澳大利亚</span><strong style="line-height: 1.5;"> &#8220;非法&#8221;购买豪宅</strong><span style="line-height: 1.5;">，遭澳大利亚当局责令90天内出售，该栋豪宅价值3,900万澳元(3,005万美元)。</span></p>
<p><span style="line-height: 1.5;">NO.7 由于删除了ISIS在推特上的相关账号，</span><strong style="line-height: 1.5;">推特</strong><span style="line-height: 1.5;">联合创始人</span><strong style="line-height: 1.5;">杰克-多尔西收到了ISIS发出的死亡威胁</strong><span style="line-height: 1.5;">，推特公司称已与相关执法机构合作展开调查。</span></p>
<p><span style="line-height: 1.5;">NO.8 </span><span style="line-height: 1.5;">有市民王女士昨日反映，她参加<strong><span class='wp_keywordlink_affiliate'></span></strong>&#8220;满199元返200元&#8221;的活动，<strong>满足返券要求的一笔订单下单后却被分成两份</strong>，导致客服误会，认为其不满足返券要求。该事目前已解决。</span></p>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c150303/14253Z0Aa0-3ZW_lit.jpg{/dede:field}
