{dede:field name='keywords'}三星,小米,苹果{/dede:field}
{dede:field name='description'}过去一年，三星手机因为缺少亮点表现糟糕。在未来一年内，三星有希望扭转这一局面，把希望寄托在了Galaxy两款旗舰机的身上——S6及S6 edge，上述两款手机刚刚在MWC2015展会前夕发布。{/dede:field}
{dede:field name='title'}【图文】三星求变：借金属边框和曲面屏，应对挑战{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='body'}<p style="text-align: center;"><img class="aligncenter size-full wp-image-198838" title="三星S6" src="/uploads/allimg/c150303/14253ZMU50-255R.jpg" alt="三星S6" width="560" height="420" /></p>
<p><strong>【钛媒编辑/曹天鹏】</strong><span class='wp_keywordlink_affiliate'></span>正在彻底改革其手机业务，以应对竞争对手更为激进的挑战。</p>
<p>过去一年，作为Android阵营的领头羊，三星手机因为缺少亮点表现糟糕，<span class='wp_keywordlink_affiliate'></span>和中国手机厂商都在一步步蚕食其手机市场份额，销量并不是很理想，利润开始出现下滑，领先优势越来越不够明显。</p>
<p>不过，在未来一年内，三星有希望扭转这一局面，把希望寄托在了Galaxy两款旗舰机的身上——S6及S6edge，上述两款手机刚刚在MWC2015展会前夕发布（北京时间3月2日凌晨）。</p>
<p>这两款手机由外向内，都发生了不小的改变。先看外观，S6换了新装，用金属边框和玻璃材质后盖，换掉了一直被用户吐槽的塑料壳，看上去不再那么廉价。S6更多细节如下：</p>
<blockquote><p>三星GALAXYS6配备了5.1英寸2K分辨率的superAMOLED屏幕，同时将屏幕的亮度提升到600nit，在色彩表现以及解析力方面表现不错。运行内存为3GB，同时配备前置500万像素+后置具备OIS防抖功能的1600万像素镜头。</p>
<p>S6同样也加入了指纹识别功能，但在技术方面支持按压式操作。系统方面，S6使用了Android5.0.2操作系统，并搭载了“瘦身”后Touchwiz界面。另外，S6还支持了无线充电，采用Qi标准，而无线充电底座应该还需要单独购买。</p></blockquote>
<p>S6Edge手机两侧都采用了曲面屏，不过这不是第一次采用曲面屏的三星手机，首次在智能手机上尝试曲面屏的是去年的GalaxyNoteEdge。S6Edge更多细节如下：</p>
<blockquote><p>S6edge在配置规格方面与S6相似，同样也配备了5.1英寸2K分辨率SuperAMOLED屏幕。和第一代曲面屏手机Noteedge相比，S6edge的屏幕从单边完全变成了两边弯曲，弯曲的弧度一样，换而言之S6edge的屏幕是完全对称的。这种设计更利于解决左右手习惯性的问题。</p>
<p>在硬件配置方面，S6edge在屏幕分辨率、运行内存、操作系统等诸多方面与S6相同。</p></blockquote>
<p>除了外观，这两款手机内在也有变化，芯片换上了三星自家的，用以代替之前的高通；为与ApplePay抗衡，三星和MasterCard和Visa合作推出了自己的支付系统SamsungPay。</p>
<p>值得一提的是，三星随S6和S6EdgeGear还推出了新的虚拟现实头戴设备GearInnovatorEdition，支持这两款设备，能获得更高质量的无线虚拟现实体验。</p>
<p>可以这么说，三星旨在提供与众不同的产品，以刺激消费者购买，来提升手机销量。如果一味缺乏创新，将被消费者抛弃。</p>
<p>尽管如此，三星仍不能掉以轻心。要知道，苹果新推出的两款大屏手机iPhone6和6+，很受欢迎；而在中低端市场，<span class='wp_keywordlink_affiliate'></span>、华为等中国竞争对手的威胁，只会增加不会减少。</p>
<p>三星能否扳回一局，就看手机（<span style="line-height: 1.5;">包含32GB、6<span class='wp_keywordlink'></span>B、128GB等多个版本</span><span style="line-height: 1.5;">）从4月10号上市之后，消费者的反应了。</span></p>
<p>&nbsp;</p>
<p><strong>以下附发布会现场图片：</strong></p>
<p><img class="aligncenter size-full wp-image-198839" title="三星S6" src="/uploads/allimg/c150303/14253ZM9320-3Ob.jpg" alt="三星S6" width="560" height="314" /></p>
<p style="text-align: center;">等候入场的记者和合作伙伴排起长队</p>
<p style="text-align: center;"><img class="aligncenter size-full wp-image-198842" title="三星S6" src="/uploads/allimg/c150303/14253ZN0540-432Q.jpg" alt="三星S6" width="560" height="420" /></p>
<p style="text-align: center;">等候发布会开始</p>
<p style="text-align: center;"><img class="aligncenter size-full wp-image-198844" title="三星S6" src="/uploads/allimg/c150303/14253ZN15Z-55257.jpg" alt="三星S6" width="560" height="420" /></p>
<p style="text-align: center;">发布会进行中</p>
<p style="text-align: center;"><img class="aligncenter size-full wp-image-198840" title="三星S6" src="/uploads/allimg/c150303/14253ZN2350-61331.jpg" alt="三星S6" width="560" height="420" /></p>
<p style="text-align: center;">发布会进行中</p>
<p style="text-align: center;"><img class="aligncenter size-full wp-image-198845" title="三星S6" src="/uploads/allimg/c150303/14253ZN3250-K626.jpg" alt="三星S6" width="560" height="267" /></p>
<p style="text-align: center;">跟iPhone对比拍照效果</p>
<p style="text-align: center;"><img class="aligncenter size-full wp-image-198847" title="三星S6" src="/uploads/allimg/c150303/14253ZN410-Wa5.jpg" alt="三星S6" width="560" height="314" /></p>
<p style="text-align: center;"><img class="aligncenter size-full wp-image-198848" title="三星S6" src="/uploads/allimg/c150303/14253ZN4960-95242.jpg" alt="三星S6" width="560" height="420" /></p>
<p style="text-align: center;"><img title="三星" src="/uploads/allimg/c150303/14253ZN5T0-10aG.jpg" alt="三星" width="560" height="420" /></p>
<p style="text-align: center;">手机体验环节</p>
<p><img class="aligncenter" title="三星S6" src="/uploads/allimg/c150303/14253ZNBP-119395.jpg" alt="三星S6" width="560" height="420" /></p>
<p style="text-align: center;">三星S6（手机左）和S6 Edge手机顶部</p>
<p style="text-align: center;"><img class="aligncenter size-full wp-image-198849" title="三星" src="/uploads/allimg/c150303/14253ZNJ0-12F08.jpg" alt="三星" width="560" height="420" /></p>
<p style="text-align: center;">三星S6（手机下）和S6 Edge手机底部</p>
<p style="text-align: center;"><img class="aligncenter size-full wp-image-198854" title="三星" src="/uploads/allimg/c150303/14253ZNQ50-139449.jpg" alt="三星" width="560" height="420" /></p>
<p style="text-align: center;">三星S6（手机下）和S6 Edge的手机右侧</p>
<p style="text-align: center;"><img class="aligncenter size-full wp-image-198851" title="三星" src="/uploads/allimg/c150303/14253ZNZ-145b3.jpg" alt="三星" width="560" height="420" /></p>
<p style="text-align: center;">三星S6（手机上）和S6 Edge的手机背部，摄像头凸起</p>
<p style="text-align: center;"><img class="aligncenter size-full wp-image-198857" title="三星" src="/uploads/allimg/c150303/14253ZN9D0-151210.jpg" alt="三星" width="560" height="420" /></p>
<p style="text-align: center;">体验S6EdgeGear</p>
<p style="text-align: center;"><img class="aligncenter size-full wp-image-198858" title="三星" src="/uploads/allimg/c150303/14253ZO0C0-1B253.jpg" alt="三星" width="560" height="420" /></p>
<p style="text-align: center;">现场工作人员</p>
<p style="text-align: center;"><img class="aligncenter size-full wp-image-198859" title="三星" src="/uploads/allimg/c150303/14253ZO1X0-1H4G.jpg" alt="三星" width="560" height="420" /></p>
<p style="text-align: center;">手机体验现场</p>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c150303/14253ZO25Z-1X616.jpg{/dede:field}
