{dede:field name='keywords'}智能手机,索尼{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}如果索尼缺席2020年的MWC展，请无须惊讶{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='body'}<p><img class="aligncenter size-large wp-image-166993" title="索尼" src="/uploads/allimg/c150303/14253Z0KG0-15246.jpg" alt="索尼" width="560" height="306" /></p>
<p><span style="line-height: 1.5;"><strong>【钛媒综述】</strong><span class='wp_keywordlink_affiliate'></span>毫无疑问是众多消费电子展会上耳熟能详的名字，特丽珑彩电、Walkman、PS系列游戏机曾为人们带来无数美好记忆，当索尼出现在巴塞罗那MWC展时，它仍有其不可忽视的影响力。BBC记者Rory Cellan-Jones再度采访索尼CEO平井一夫，发文认为索尼的移动通信业务不可持久。</span></p>
<p><span style="line-height: 1.5;">新品发布络绎不绝的巴塞罗那MWC展上，索尼推出传闻已久的超轻薄款Z4 Tablet，同时低调发布定位于中低端的手机产品Xperia M4 Aqua，但目前并没有关于其旗舰智能机Z4的发布消息。</span></p>
<p>针对此前媒体纷纷推测索尼将退出手机及电视机业务的报道，索尼移动通信部门负责人Hiroki Totoki予以否认，并称平井一夫也现身巴塞罗那足见公司对移动业务的重视；他同时也表示，移动部门的产品生产线布局太过分散，同时公司将考虑减慢新产品推出的节奏。</p>
<p>另外，<strong>昨日晚间海信电器也发布公告，否认将接手索尼电视业务</strong>。</p>
<p>BBC通讯记者Rory Cellan-Jones认为索尼在巴塞罗那展会上的新品虽然吸引人，但独特性和市场影响力有限。与两年前对手机业务雄心勃勃的索尼和平井一夫不同，如今索尼在IDC的手机市场研报中已经被归于“others”一栏，远远落后于苹果、三星，更被小米、华为等中国手机厂商甩在后面，索尼移动通信部门成了索尼集团亏损的主因之一。</p>
<p>被问到“索尼是不是该放弃移动业务”时，平井一夫表示“手机市场竞争激烈、变化迅速，在某些市场区域，索尼一直疲于追赶。索尼需要更加关注资本回报，但这并不意味着我们要放弃这一块（移动业务）”，<strong>此前几周，平井一夫承认移动通信业务并非索尼未来命脉所系，而更看重索尼娱乐部门的增长潜力。</strong></p>
<p>在平井一夫的两年CEO任期内，除了温和易处，他还展示了自己在必要时能够下得了狠手的残酷一面，以尽量维持索尼的市值底盘。</p>
<p>Rory Cellan-Jones问道：</p>
<blockquote><p>“索尼能确保五年后还在坚持做手机业务吗”？</p></blockquote>
<p>平井一夫：</p>
<blockquote><p>“谁也无法确定五年后索尼在做什么业务，电子产品市场的特点就是这样。”</p></blockquote>
<p>五年前，诺基亚和黑莓还是手机市场的统治级巨头，现在二者一死一衰，早已物是人非。所以如果索尼缺席2020年MWC展，请无须惊讶。</p>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c150303/14253Z0KG0-15246_lit.jpg{/dede:field}
