<li style="z-index: 1; opacity: 0; ">
<a href="[field:arcurl/]" target="_blank">
<img src="[field:litpic/]" alt="[field:title/]" style="width: 744.1176470588235px; height: 330px; margin-left: -42.05882352941177px; margin-top: 0px; "></a>
<div class="ei-title">
<h2 style="display: block; opacity: 0; "><a href="[field:arcurl/]" target="_blank">[field:title/]</a></h2>
<h3 style="display: block; opacity: 0; "><a href="[field:arcurl/]" target="_blank">[field:infos/]...</a></h3>
</div>
</li>