{dede:field name='keywords'}P2P,财报,金融{/dede:field}
{dede:field name='description'}Lending Club上市过程一直备受瞩目，不过昨日公布的上市后首季财报并不乐观：第四季度营收为6810万美元，高于去年同期的3350万美元；净亏损为900万美元，平均每股亏损7美分，不及2013年同期业绩，而2013年第四季度Lending club净利润为290万美元。{/dede:field}
{dede:field name='title'}Lending Club首份财报净亏损900万美元，引发股价下跌{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='body'}<p><img class="aligncenter size-medium wp-image-197852" title="lendingclub" src="/uploads/allimg/c150303/14253Z922430-Ua5.jpg" alt="" width="400" height="265" /></p>
<p>作为全球第一大<span class='wp_keywordlink_affiliate'></span>网贷公司，Lending Club上市过程一直备受瞩目，不过昨日公布的上市后首季<span class='wp_keywordlink_affiliate'></span>并不乐观：<strong>第四季度营收为6810万美元，高于去年同期的3350万美元；净亏损为900万美元，平均每股亏损7美分</strong>，不及2013年同期业绩，而2013年第四季度Lending club净利润为290万美元。</p>
<p>此前雅虎财经统计数据显示，分析师平均预期lendingClub第四季度营收为6667万美元，实际上LendingClub第四季度营收为6810万美元，高于去年同期3350万美元，超出分析师预测。</p>
<p>受财报影响，当日Lending Club股价在纽约证券交易所常规交易中下跌0.11美元，报收于23.65美元，跌幅为0.46%。在盘后交易中，Lending Club股价再度下跌至21.24美元，跌幅为10.19%。Lending Club成立8年，于2014年12月初上市，挂牌价为每股15美分，高于此前设定的每股12-14美元的发行价区间，上市首日Lending Club股价收盘大幅上涨56%，报23.43美元。在过去52周里，Lending Club的最高股价为29.29美元，最低股价为18.30美元。</p>
<p align="left">Lending Club预计，2015财年第一季度公司营收将在7400万美元到7600万美元，调整后EBITDA（未计入利息、税项、折旧及摊销的盈利）将在600万美元到900万美元之间；2015财年该公司的营收将在3.7亿美元到3.8亿美元之间，调整后EBITDA将在3300万美元到4200万美元之间。</p>
<p>Lending Club首席执行官雷诺德·拉普朗什非常乐观，他表示：<strong>公司目前尚未关注利润率情况，未来将会继续加大力度投资产品与技术。</strong>他对这一季度公司的表现很满意，Lending Club在信用卡再融资市场潜力巨大，正在向小企业贷款市场挺进，此外还收购了创业公司Springstone，进入教育贷款以及非常规医药融资领域。</p>
<p>小企业市场贷款潜力巨大。<span class='wp_keywordlink'></span>记者了解到，今年2月初Lending Club与阿里巴巴合作，将向这家中国电商巨头的美国客户提供小额商业贷款，这款融资工具被阿里巴巴命名为“e-credit”,可以提供高达30万美元的贷款，贷款流程不到5分钟。<strong>这意味着Lending Club目前开始尝试新型贷款业务并与其他公司达成合作，以维持自身的快速发展。</strong></p>
<p>Lending Club的上市曾鼓舞了众多国内P2P网贷平台，不过，中美P2P网贷平台生存环境不同，美国信用体系、征信工作完备，政府信息共享，借款人大多是信用卡领域的个人消费金，可以做纯粹线上的网贷业务；国内信息不对称，借款人主要是小微企业主、手工行业者、个人雇佣者，没有被征信覆盖，纯粹做线上业务会很难，Lending Club对于国内平台并无太多借鉴意义。</p>
<p><strong>即便</strong><strong>P2P</strong><strong>平台上市，成为公众公司，也将面对更多压力，比如财报信息公开、股价起伏跌宕。所以上市不是目的，只是平台获得更多融资杠杆、发展自身业务的途径而已。（本文首发钛媒体）</strong><strong></strong></p>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c150303/14253Z922P-93004.jpg{/dede:field}
