{dede:field name='keywords'}钛媒体,钛媒体公告,钛度奖{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}duang！春节前后（2.9—3.1）码字停不下来，十篇文章不容错过{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='body'}<p></p>
<p>新年好呀，小钛又跟大家见面了！刚刚过去的春节假期，大家是怎么度过的呢？是抢红包呢，还是抢红包呢，哈哈。小钛知道，很多作者在春节期间也在坚持码字，分享自己独到的见解给<span class='wp_keywordlink'></span>的朋友们。</p>
<p>好内容值得嘉奖！根据春节前后（2.9—3.1）<span class='wp_keywordlink_affiliate'></span>收到的大量投稿统计，参考用户访问、好评度、是否独家发表等综合因素，选出了10个作者的10篇文章，寓意十全十美。<strong>为了感谢这些作者一直以来对的陪伴与支持，入选文章都将获得当月“”的奖励，得到专属稿费和激励</strong>（<em>查看之前获奖文章可以点击</em><em>）</em>。</p>
<p>&nbsp;</p>
<p>好稿名单：</p>
<p>1、，作者个人页面：</p>
<p>2、，作者个人页面：</p>
<p>3、，作者个人页面：</p>
<p>4、，作者个人页面：</p>
<p>5、，作者个人页面：</p>
<p>6、，作者个人页面：</p>
<p>7、，作者个人页面：</p>
<p>8、，作者个人页面：</p>
<p>9、，作者个人页面：</p>
<p>10、，作者个人页面：</p>
<p>&nbsp;</p>
<p>以上文章排名不分先后，具体<span class='wp_keywordlink_affiliate'></span>排名将稍后发布。</p>
<p><em>【重！要！提！示！】为了组织发奖，运营组同学将提前收集领奖账户信息。由于部分作者是最近几个月的新晋作者，请各位作者及时认真看清楚榜单，及时联系运营组同学，提供个人身份证号码、联系方式、真实姓名、银行卡开户行（至少具体到市级）及卡号（暂不接受支付宝）等信息。当然，接下来的一周内会陆续有运营组同学面带微笑骚扰各位，索要领奖账户噢！</em></p>
<p><em>上述领奖信息请发送至邮箱：，</em><em>或站内留言给编辑：佳音。</em></p>
<p><strong></strong></p>
<p><strong>还不知道怎么投稿？</strong></p>
<p>很简单，只需要你先注册成为钛媒体用户，就可以通过用户中心投稿啦——在导航栏最右边轻轻一点“我要投稿”，Bingo！投稿要求和详细的选稿标准，我们期待更多的分享和独立思考。</p>{/dede:field}
{dede:field name='litpic'}{/dede:field}
