<?php
$z[0]=Array("arcurl","",42,57);
$z[1]=Array("title","",66,80);
$z[2]=Array("title","",82,96);
$z[3]=Array("pubdate","",130,181);
$z[3][4]['function']="MyDate('YÄêmÔÂdÈÕ',@me)";
$z[4]=Array("click","",188,202);
$z[5]=Array("typeurl","",224,240);
$z[6]=Array("typename","",253,270);
$z[7]=Array("typename","",282,299);
$z[8]=Array("arcurl","",355,370);
$z[9]=Array("title","",379,393);
$z[10]=Array("litpic","",431,446);
$z[11]=Array("title","",482,496);
$z[12]=Array("infos","",539,553);
$z[13]=Array("arcurl","",587,602);

?>