<?php
$z[0]=Array("arcurl","",44,59);
$z[1]=Array("title","",68,82);
$z[2]=Array("title","",84,98);
$z[3]=Array("pubdate","",140,191);
$z[3][4]['function']="MyDate('YÄêmÔÂdÈÕ',@me)";
$z[4]=Array("click","",198,212);
$z[5]=Array("typeurl","",242,258);
$z[6]=Array("typename","",271,288);
$z[7]=Array("typename","",300,317);
$z[8]=Array("arcurl","",378,393);
$z[9]=Array("title","",402,416);
$z[10]=Array("litpic","",458,473);
$z[11]=Array("title","",509,523);
$z[12]=Array("description","",576,596);
$z[13]=Array("arcurl","",630,645);

?>