<div class="recent-item">		
<div class="post-thumbnail" style="height:93px;overflow:hidden;">
<a href="[field:arcurl/]" title="[field:title/]?" target="_blank">				
<img src="[field:litpic/]" alt="?[field:title/]">
  <span class="overlay-icon"></span>
</a>
</div>
<h3><a href="[field:arcurl/]" title="?[field:title/]" target="_blank">?[field:title/]</a></h3>
<p class="post-meta">
[field:pubdate function="MyDate('Y年m月d日',@me)"/] 		查看：	[field:click/] 		</p>
</div>