<?php
$z[0]=Array("arcurl","",64,79);
$z[1]=Array("arcurl","",109,124);
$z[2]=Array("title","",149,163);
$z[3]=Array("litpic","",177,192);
$z[4]=Array("title","",199,213);
$z[5]=Array("typename","",272,289);
$z[6]=Array("arcurl","",318,333);
$z[7]=Array("title","",335,349);
$z[8]=Array("description","",363,383);
$z[9]=Array("writer","",404,420);
$z[10]=Array("pubdate","",433,479);
$z[10][4]['function']="GetDateTimeMK(@me)";

?>