{dede:field name='keywords'}创业,商业模式,硅谷新公司{/dede:field}
{dede:field name='description'}Lavanda将自己定位为“洗衣领域的Uber”，用户之前并不需要预定，有了需求直接下单，附近可以提供运送或者洗衣服务的人在25分钟内可以相应你的需求。{/dede:field}
{dede:field name='title'}【硅谷新公司】Lavanda：洗衣服务行业的Uber{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='body'}<p><img class="size-large wp-image-197914 aligncenter" src="/uploads/allimg/c150303/14253ZQ3150-525A.jpg" alt="" width="560" height="339" /></p>
<p><strong>】为特色栏目，连线记者站，每日速递，、新模式新动态）</strong></p>
<p>Lavanda是一家最新的按需洗衣服务的初创公司，其创始人Guy Westlake此前是一小时送货公司Shutl的市场总监。</p>
<p>Lavanda将自己定位为“洗衣领域的Uber”，该服务近日正式上线，并融资了26.5万美金将业务继续扩大至伦敦以外的地方，同时其iOS和Android版的App也有望在接下来的几个星期内面世。</p>
<p>本轮投资者包括Samos Investments的合伙人Ned Cranborne、Shutl的创始人Tom Allason、Shutl的CTO Stephen Romney、what3words的联合创始人Jack Waley-Cohen和Michael Dent以及3 Kinds of Ice的联合创始人Hugo Adams。</p>
<p>可以看到投资人中有两个人都来自于Shutl，它可以在运送和物流环节与Lavanda达成战略共赢。怪不得Lavanda将自己称为真正的按需定制的服务，从用户下单到上门取件仅需要不到25分钟的时间。</p>
<p>Lavanda拥有一个Westlake称之为超本地化的洗衣自雇者的网络，这个网络由附近可以灵活地提供运送或者洗衣服务的人组成。这些洗衣自雇者在自己家中完成洗衣任务，通常这些人是在家办公的妈妈或者人群，比如儿童保姆等，他们平时就要做一些洗衣的工作。<img class="size-large wp-image-197915 aligncenter" src="/uploads/allimg/c150303/14253ZQ4120-C532.png" alt="" width="560" height="295" /></p>
<p>Lavanda<span class='wp_keywordlink_affiliate'></span>的最大特点是将洗衣任务派发给普通人，而其竞争对手，虽然也致力于通过手机App方便地提供洗衣服务，但是却把洗衣任务外包给合作的洗衣房或者其它公司。而相比之下，Lavanda是Uber的模式，用户之前并不需要预定，有了需求直接下单就可以。（<strong>本文首发<span class='wp_keywordlink'></span></strong>）</p>
<p><strong>（本栏目中的项目皆由搜集、整理）</strong></p>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c150303/14253ZQ6350-L457.jpg{/dede:field}
