{dede:field name='keywords'}三星,投稿,移动支付,苹果,谷歌{/dede:field}
{dede:field name='description'}这么快三星就在MWC2015大会发布Samsung Pay还是让人有些出乎意料，三星已经正式加入移动支付的混战，与苹果Apple Pay、谷歌的Google Wallet，eBay的Paypal、沃尔玛等的Current C贴身近战，究竟谁的胜算更大？{/dede:field}
{dede:field name='title'}三星入局移动支付混战：谷歌苹果三星沃尔玛Paypal谁的胜算更大？{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='body'}<p><img class="aligncenter size-medium wp-image-199126" title="三星" src="/uploads/allimg/c150303/14253Z0PV0-3X08.jpg" alt="" width="400" height="281" /></p>
<p><span class='wp_keywordlink_affiliate'></span>2月收购美国<span class='wp_keywordlink_affiliate'></span>公司Loop Pay已经让大家明白了其进军移动支付的野心，不过这么快三星就在MWC2015大会发布Samsung Pay还是让人有些出乎意料。三星已经正式加入移动支付的混战，与<span class='wp_keywordlink_affiliate'></span>Apple Pay、<span class='wp_keywordlink_affiliate'></span>的Google Wallet，eBay的Paypal、沃尔玛等的Current C贴身近战，究竟谁的胜算更大？</p>
<p>&nbsp;</p>
<p><strong>三星高调进入移动支付市场 兼容磁条设备成为杀手锏</strong></p>
<p>三星周日发布Galaxy S6手机和Samsung Pay支付服务，<strong>Samsung Pay与其他支付服务最大的一点不同是除了支持NFC技术外还可以向下兼容磁条卡刷卡机</strong>，而目前美国已有90%的收银机支持磁条卡刷卡， Samsung Pay对于不希望更换收银机的商户更有吸引力，装备NFC设备的收银机更换有成本，故而美国一些小型商店没有升级计划，也无法加入支持Apple Pay和Google Wallet的阵营。</p>
<p>除了兼容性好之外，从三星公布的描述看，Samsung Pay的便利性和安全性也不错。Samsung Pay也是通过指纹扫描验证支付，然后通过与商户的收银机终端接触即可完成支付，安全方面三星采用KNOX和ARM的TrustZone来保护用户支付数据安全。</p>
<p>不过三星还在与Visa和MasterCard协商合作细节，具体推出时间是下半年，预计先后进入美国、韩国、欧洲以及中国市场，不过涉及许多银行的合作细节具体的推出时间自然未确定。</p>
<p>&nbsp;</p>
<p><strong>移动支付的混战各方：谷歌有先机 苹果更引人注目</strong></p>
<p>移动支付市场在苹果公司杀入前，一直是波澜不惊，大家都知道要做，不过进展缓慢，苹果作为最成功的手机公司，杀入移动支付后引发了市场翻天覆地的变化，各家的投入都在大增，Apple Pay已经有百万用户，随着商户收银机以及用户手机等硬件的更新换代，2015年会成为用户迁移和适应移动支付的重要一年。</p>
<p><span style="line-height: 1.5;">苹果的Apple Pay毫无疑问是目前移动支付战役的明星，不过Apple Pay需要依靠支持近场通信(NFC)技术的收银机，此前苹果公司宣布有22万家商户支持而此后没有再公布过数据，美国有超过600万家商户，除了抵制的连锁超市外，苹果要一家一家谈也是蛮耗时耗力的事情。不过有分析师认为，随着信用卡组织和银行等发卡商从磁条卡转向芯片卡，以及各种移动支付对NFC的推动，商户安装NFC的收银机的数量在近2年会爆炸式的增长。</span></p>
<p>谷歌此前是移动支付市场的领先者，2011年就已经进入，在谷歌手机中也早就预装了NFC设备，不过谷歌的悲哀在于看到了市场但领先太多市场还没有做好准备，并且没有竞争的市场让谷歌的推进很迟缓。Apple Pay的迅速流行，让自认为把握先机的谷歌无法稳坐钓鱼台，Google Wallet和Apple Pay十分依赖NFC技术，NFC之前推动的缓慢也是Google Wallet止步不前的一个原因，不过有了苹果携iPhone 6强势杀入后，市场开始重视移动支付，随着安装NFC设备的收银机增多，情势应该会慢慢改观，苹果和谷歌是NFC技术的主要推动者，也因为公司本身的财大气粗（话说加入移动支付的谁不是，不过谷歌和苹果更重视移动支付的卡位）两家开始的厮杀肯定会很严重。</p>
<p>PayPal在PC时代积累了大量的用户，这些人都是很好的移动支付潜在用户，所以eBay也不是没有机会。</p>
<p>沃尔玛等超级零售连锁商，因为不满信用卡组织和银行的“高额”手续费，组建MCX联盟，推出Current C，他们也因此不参加支持Apple Pay的阵营，不过Current C被吐槽技术原始，何时能推出还不好说。</p>
<p>三星兼容磁条卡刷卡技术目前看起来最讨巧，美国有很多知变通的经营者，不过也有很多老店不愿意支付更换设备的成本，三星支付就看好了这个切入点。不过三星需要解决的最大问题是，Samsung Pay真实使用效果像推介的那么方便，以及三星能卖出数量足够多的新手机，也许后者才是三星的大问题，从三星一贯的售价策略看，Galaxy S6还是很贵的高端机，而美国的大屏手机用户要不已经用上上一代Galaxy，要不已经投奔iPhone，以美国用户缓慢的换机速度，Samsung Pay的路还有很长。</p>
<p>&nbsp;</p>
<p><strong>综合来看，移动支付的混战各方各有优势和劣势</strong></p>
<p>谷歌的优势在于进入市场早，技术积累足够，并且与Softcard合作可以让Google Wallet装入美国三大电信运营商的Android手机中，总量上甚至可能比iPhone更多。不过支持NFC的设备少始终是一个软肋。</p>
<p>苹果公司的优势在于不需要做什么，就有媒体和个人免费宣传Apple Pay，并且谷歌辛辛苦苦劝说商户安装的NFC设备都为苹果做了嫁衣，但苹果公司的问题在于NFC的设备少，以及依靠iPhone这一单一设备推动Apple Pay，不知Apple Watch发布后会不会有所改观。</p>
<p>三星使用LoopPay的技术，可以让美国众多小商户接受起来没成本，不过三星受限于终端的发售速度。</p>
<p>沃尔玛领衔的零售巨头也不是没有机会，因为受了信用卡组织很多年的气，加上零售的利润逐年降低，沃尔玛振臂一呼后有Rite Aid, CVS等重量连锁商加入，现在的问题就是CurrentC通过扫描二维码来完成支付，不够便捷，完全是上一代的技术，CurrentC的易用性还没有得到用户验证。</p>
<p>移动支付是方便快捷许多，不过old habits die hard，有朋友认为刷卡也不慢，对于各家号称安全的移动支付还需要观察，万一黑客能攻克某家的服务器，自己的财务支付信息可就完全暴露了。</p>
<p>移动支付的战幕已经开启，金融是经济活动的皇冠上的明珠，看好的企业很多目前不知还会有什么样的公司打算加入，现在的各方都拼命利用优势抢占先机，鹿死谁手就拭目以待了。</p>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c150303/14253ZA63Z-5XZ.jpg{/dede:field}
