{dede:field name='keywords'}TMT行业观点平台,科技媒体,互联{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}LinkedIn2014第一季度净亏1340万美元{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='body'}<p>
				<p><img class="aligncenter size-large wp-image-108276" title="LinkedIn" src="/uploads/allimg/c140503/13c10Y10J0-34326.jpg" alt="" width="560" height="350" /></p>
<p>5月2日消息，据外国媒体报道，美国职业社交网站<span class='wp_keywordlink_affiliate'><a href="http://www.tmtpost.com/tag/linkedin" title="查看 LinkedIn 中的全部文章" target="_blank">LinkedIn</a></span>今天公布了其截至3月31日的2014年第一季度的财务报告。按照报告显示，2014年第一季度，LinkedIn营收为4.732亿美元，同比增长46%；归属于普通股股东的净亏损为1340万美元，去年同期归属于普通股股东的净利润为2260万美元。</p>
<p>2014年第一季度，LinkedIn营收为4.732亿美元，比去年同期的3.247亿美元增长46%。</p>
<p>2014年第一季度，LinkedIn归属于普通股股东的净亏损为1340万美元，去年同期净利润为2260万美元。2014年第一季度，LinkedIn不纳入税收影响的股权奖励支出和无形资产摊销费用等在内的非美国通用会计准则的净利润为4730万美元，去年同期该利润为5240万美元。</p>
<p>2014年第一季度，LinkedIn经调整后的EBITDA(即未计入利息、税费、折旧和摊销前净利润)为1.167亿美元，占季度总营收的25%；去年同期经调整后的EBITDA利润为8340万美元，占当时季度总营收的26%。</p>
<p>2014年第一季度，LinkedIn符合美国通用会计准则的每股稀释亏损为0.11美元，去年同期每股稀释利润为0.20美元；非美国通用会计准则的净利润为0.38美元，去年同期为0.45美元。</p>
<p><strong>各产品业务表现：</strong></p>
<p>2014年第一季度，LinkedIn来自人才解决方案产品的营收共为2.759亿美元，同比增长50%，约占第一季度总营收的58%，去年同期这一比例为57%。</p>
<p>2014年第一季度，LinkedIn来自于营销解决方案产品的营收为1.018亿美元，同比增长36%；第一季度营销解决方案营收在季度总营收中的比例为22%，去年同期这一比例为23%。</p>
<p>2014年第一季度，LinkedIn来自于优质收费订阅产品的营收为9550万美元，同比增长46%；第一季度优质订阅产品的营收在季度总营收中的比例为20%，与去年同期持平。</p>
<p><strong>各地区业务表现：</strong></p>
<p>2014年第一季度，LinkedIn来自于美国市场业务的营收为2.849亿美元，占季度总营收的60%。</p>
<p>2014年第一季度，LinkedIn来自于国际市场业务的营收为1.883亿美元，占季度总营收的40%。</p>
<p>各销售渠道表现：</p>
<p>2014年第一季度，LinkedIn来自于实地销售渠道的营收为2.753亿美元，占季度总营收的58%。</p>
<p>2014年第一季度，LinkedIn来自于网络直销渠道的营收为1.979亿美元，占季度总营收的42%。</p>
<p><strong>业务预期：</strong></p>
<p>LinkedIn预期其2014年第二季度营收将达到5亿美元至5.05亿美元之间；预期经调整后的EBITDA利润将达到1.18亿美元至1.2亿美元之间；预期折旧和摊销开支约为5300万美元，预期股权奖励支出约为7500万美元。</p>
<p>LinkedIn预期其2014年全年营收将达到20.6亿美元到20.8亿美元之间；预期经调整后的EBITDA利润将达到5.05亿美元至5.1亿美元之间；预期折旧和摊销开支约为2.25亿美元；预期股权奖励开支约为3.05亿美元。（牛牛）</p>
			
				<p></><span>（关注更多<a href="http://www.tmtpost.com/">钛媒体</a>作者观点，参与钛媒体微信互动（微信搜索“钛媒体”或“taimeiti”））</span></p>
			</p>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c140503/13c10Y10J0-34326_lit.jpg{/dede:field}
