<div class="hotbox">
<div class="hotimg">
<div class="hotimgzz"></div>
<img src="[field:litpic/]" alt="[field:title/]" width="250" height="165">
<div class="standpoint">[field:typename/]</div>
<a class="zzsz" href="[field:arcurl/]" target="_blank" title="[field:title/]"></a>
</div>
<h3><a href="[field:arcurl/]">[field:title/]</a></h3>
<p>[field:description/]...</p>
<span>×÷Õß£º[field:writer /]</span><span>[field:pubdate function="GetDateTimeMK(@me)"/]</span> 
</div>