<?php
$z[0]=Array("global","",34,61);
$z[0][4]['name']="cfg_basehost";
$z[1]=Array("global","",76,102);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("global","",314,341);
$z[2][4]['name']="cfg_basehost";
$z[3]=Array("global","",418,445);
$z[3][4]['name']="cfg_basehost";
$z[4]=Array("global","",448,474);
$z[4][4]['name']="cfg_webname";
$z[5]=Array("global","",510,537);
$z[5][4]['name']="cfg_basehost";
$z[6]=Array("global","",664,691);
$z[6][4]['name']="cfg_basehost";
$z[7]=Array("channel","\r\n<li><a href='[field:typelink/]'>[field:typename/]</a> </li>\r\n",710,887);
$z[7][4]['type']="top";
$z[7][4]['currentstyle']="<li><a href='~typelink~' class='cur'>~typename~</a> </li>";
$z[8]=Array("tag","\r\n<a href='[field:link/]'>[field:tag /]</a>\r\n",995,1093);
$z[8][4]['sort']="rand";
$z[8][4]['getall']="1";
$z[8][4]['row']="12";
$z[9]=Array("global","",1198,1223);
$z[9][4]['name']="cfg_cmsurl";
$z[10]=Array("global","",1346,1378);
$z[10][4]['name']="cfg_templets_skin";

?>