<?php
$z[0]=Array("global","",249,275);
$z[0][4]['name']="cfg_webname";
$z[1]=Array("global","",319,349);
$z[1][4]['name']="cfg_description";
$z[2]=Array("global","",386,413);
$z[2][4]['name']="cfg_keywords";
$z[3]=Array("include","",1256,1291);
$z[3][4]['filename']="head.htm";
$z[4]=Array("channel","\r\n<li><a href='[field:typelink/]'>[field:typename/]<i></i></a> </li>\r\n",1884,2081);
$z[4][4]['type']="son";
$z[4][4]['row']="8";
$z[4][4]['currentstyle']="<li class='on'><a href='~typelink~'>~typename~<i></i></a> </li>";
$z[5]=Array("field","",2177,2206);
$z[5][4]['name']="position";
$z[6]=Array("field","",2238,2267);
$z[6][4]['name']="typename";
$z[7]=Array("field","",2296,2317);
$z[7][4]['name']="content";
$z[8]=Array("include","",2434,2471);
$z[8][4]['filename']="footer.htm";

?>