<?php
$z[0]=Array("arclist","\r\n								<li>\r\n		<div class=\"post-thumbnail\">\r\n			<a href=\"[field:arcurl/]\" title=\"[field:title/]\">\r\n			<img src=\"[field:litpic/]\" alt=\"[field:title/]\" width=\"80\" height=\"50\"></a>\r\n		</div>\r\n	<h3><a href=\"[field:arcurl/]\">[field:title/]</a></h3>\r\n	 <span class=\"date\">[field:pubdate function=\"MyDate('Y年m月d日',@me)\"/]</span>\r\n</li>\r\n",490,907);
$z[0][4]['orderby']="click";
$z[0][4]['row']="10";
$z[0][4]['titlelen']="48";
$z[0][4]['type']="image";
$z[1]=Array("arclist","\r\n								<li>\r\n		<div class=\"post-thumbnail\">\r\n			<a href=\"[field:arcurl/]\" title=\"[field:title/]\">\r\n			<img src=\"[field:litpic/]\" alt=\"[field:title/]\" width=\"80\" height=\"50\"></a>\r\n		</div>\r\n	<h3><a href=\"[field:arcurl/]\">[field:title/]</a></h3>\r\n	 <span class=\"date\">[field:pubdate function=\"MyDate('Y年m月d日',@me)\"/]</span>\r\n</li>\r\n",1399,1815);
$z[1][4]['orderby']="rand";
$z[1][4]['row']="10";
$z[1][4]['titlelen']="48";
$z[1][4]['type']="image";
$z[2]=Array("arclist","\r\n								<li>\r\n		<div class=\"post-thumbnail\">\r\n			<a href=\"[field:arcurl/]\" title=\"[field:title/]\">\r\n			<img src=\"[field:litpic/]\" alt=\"[field:title/]\" width=\"80\" height=\"50\"></a>\r\n		</div>\r\n	<h3><a href=\"[field:arcurl/]\">[field:title/]</a></h3>\r\n	 <span class=\"date\">[field:pubdate function=\"MyDate('Y年m月d日',@me)\"/]</span>\r\n</li>\r\n",2248,2664);
$z[2][4]['orderby']="rand";
$z[2][4]['row']="10";
$z[2][4]['titlelen']="48";
$z[2][4]['type']="image";

?>