<?php
$z[0]=Array("field","",119,138);
$z[0][4]['name']="title";
$z[1]=Array("global","",139,165);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("field","",206,235);
$z[2][4]['name']="keywords";
$z[3]=Array("field","",275,333);
$z[3][4]['name']="description";
$z[3][4]['function']="html2text(@me)";
$z[4]=Array("include","",1020,1055);
$z[4][4]['filename']="head.htm";
$z[5]=Array("field","",1497,1525);
$z[5][4]['name']="typeurl";
$z[6]=Array("field","",1527,1556);
$z[6][4]['name']="typename";
$z[7]=Array("field","",1607,1636);
$z[7][4]['name']="typename";
$z[8]=Array("tag","\r\n            <a href='[field:link/]' class='tagc[field:highlight /]'>[field:tag /]</a>\r\n            ",1810,1952);
$z[8][4]['row']="60";
$z[8][4]['sort']="new";
$z[9]=Array("tag","\r\n            <a href='[field:link/]' class='tagc[field:highlight /]'>[field:tag /]</a>\r\n            ",2075,2219);
$z[9][4]['row']="90";
$z[9][4]['sort']="month";
$z[10]=Array("tag","\r\n            <a href='[field:link/]' class='tagc[field:highlight /]'>[field:tag /]</a>\r\n            ",2342,2486);
$z[10][4]['row']="100";
$z[10][4]['sort']="rand";
$z[11]=Array("include","",2579,2619);
$z[11][4]['filename']="right_tag.htm";
$z[12]=Array("include","",2692,2729);
$z[12][4]['filename']="footer.htm";

?>