<?php
$z[0]=Array("field","",255,274);
$z[0][4]['name']="title";
$z[1]=Array("global","",275,301);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("field","",342,371);
$z[2][4]['name']="keywords";
$z[3]=Array("field","",411,469);
$z[3][4]['name']="description";
$z[3][4]['function']="html2text(@me)";
$z[4]=Array("global","",487,514);
$z[4][4]['name']="cfg_basehost";
$z[5]=Array("include","",596,631);
$z[5][4]['filename']="head.htm";
$z[6]=Array("field","",676,705);
$z[6][4]['name']="position";
$z[7]=Array("tag","\r\n  <li><a href='[field:link/]' class='tagc[field:highlight /]'>[field:tag /]</a></li>\r\n ",770,900);
$z[7][4]['row']="60";
$z[7][4]['sort']="new";
$z[8]=Array("tag","\r\n  <li><a href='[field:link/]' class='tagc[field:highlight /]'>[field:tag /]</a></li>\r\n ",960,1092);
$z[8][4]['row']="60";
$z[8][4]['sort']="month";
$z[9]=Array("tag","\r\n  <li><a href='[field:link/]' class='tagc[field:highlight /]'>[field:tag /]</a></li>\r\n ",1156,1288);
$z[9][4]['row']="100";
$z[9][4]['sort']="rand";
$z[10]=Array("include","",1309,1346);
$z[10][4]['filename']="footer.htm";

?>