<?php
$z[0]=Array("field","",119,138);
$z[0][4]['name']="title";
$z[1]=Array("global","",139,165);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("field","",206,235);
$z[2][4]['name']="keywords";
$z[3]=Array("field","",275,333);
$z[3][4]['name']="description";
$z[3][4]['function']="html2text(@me)";
$z[4]=Array("include","",1023,1058);
$z[4][4]['filename']="head.htm";
$z[5]=Array("field","",1493,1512);
$z[5][4]['name']="title";
$z[6]=Array("field","",1577,1596);
$z[6][4]['name']="title";
$z[7]=Array("arclist","\r\n					<li style=\"z-index: 1; opacity: 0; \">\r\n							<a href=\"[field:arcurl/]\" target=\"_blank\">\r\n								<img src=\"[field:litpic/]\" alt=\"[field:title/]\" style=\"width: 744.1176470588235px; height: 330px; margin-left: -42.05882352941177px; margin-top: 0px; \"></a>\r\n							<div class=\"ei-title\">\r\n					<h2 style=\"display: block; opacity: 0; \"><a href=\"[field:arcurl/]\" target=\"_blank\">[field:title/]</a></h2>\r\n					<h3 style=\"display: block; opacity: 0; \"><a href=\"[field:arcurl/]\" target=\"_blank\">[field:infos/]...</a></h3>\r\n				</div>\r\n			</li>\r\n",1892,2517);
$z[7][4]['flag']="f";
$z[7][4]['limit']="0,6";
$z[7][4]['titlelen']="60";
$z[7][4]['infolen']="250";
$z[8]=Array("arclist","\r\n<li style=\"max-width: 20%; width: 16.666666666666668%; \"><a href=\"[field:arcurl/]\">[field:title/]</a> <img src=\"[field:litpic/]\"></li>\r\n",2743,2961);
$z[8][4]['flag']="f";
$z[8][4]['limit']="0,6";
$z[8][4]['titlelen']="60";
$z[8][4]['infolen']="250";
$z[9]=Array("list","\r\n				<article class=\"item-list\">\r\n		<h2><a href=\"[field:arcurl/]\" title=\"[field:title/]\">[field:title/]</a></h2>\r\n		<p class=\"post-meta\">\r\n						[field:pubdate function=\"MyDate('Y年m月d日',@me)\"/] 查看：[field:click/] \r\n								所属栏目：<a href=\"[field:typeurl/]\" title=\"查看[field:typename/]的全部内容\">[field:typename/]</a></p>							\r\n		<div class=\"post-thumbnail\">\r\n			<a href=\"[field:arcurl/]\" title=\"[field:title/]\">\r\n				<img width=\"150\" height=\"75\" src=\"[field:litpic/]\" class=\"attachment-thumbnail\" alt=\"[field:title/]\">			</a>\r\n		</div>\r\n					<div class=\"entry\">\r\n			<p>[field:description/]... 			<a class=\"more-link\" href=\"[field:arcurl/]\">阅读更多 ?</a></p>\r\n		</div>					\r\n	</article>\r\n	",3510,4263);
$z[9][4]['pagesize']="16";
$z[9][4]['titlelen']="48";
$z[10]=Array("pagelist","",4337,4403);
$z[10][4]['listitem']="index,end,pre,next,pageno";
$z[10][4]['listsize']="3";
$z[11]=Array("include","",4461,4501);
$z[11][4]['filename']="right_tag.htm";
$z[12]=Array("include","",4579,4616);
$z[12][4]['filename']="footer.htm";

?>