<?php  exit();
/*
Page: /plus/ad_js.php?aid=2
Error: 无法使用数据库
Time2014-06-14 10:11:32
*/
?>
<?php  exit();
/*
Page: /plus/ad_js.php?aid=2
Error: No database selected <br />Error sql: <font color='red'>SELECT * FROM `dede_myad` WHERE aid='2' LIMIT 0,1;</font>
Time2014-06-14 10:11:32
*/
?>
<?php  exit();
/*
Page: /plus/ad_js.php?aid=4
Error: 无法使用数据库
Time2014-06-14 10:11:32
*/
?>
<?php  exit();
/*
Page: /plus/ad_js.php?aid=4
Error: No database selected <br />Error sql: <font color='red'>SELECT * FROM `dede_myad` WHERE aid='4' LIMIT 0,1;</font>
Time2014-06-14 10:11:32
*/
?>
<?php  exit();
/*
Page: /plus/ad_js.php?aid=3
Error: 无法使用数据库
Time2014-06-14 10:11:33
*/
?>
<?php  exit();
/*
Page: /plus/ad_js.php?aid=3
Error: No database selected <br />Error sql: <font color='red'>SELECT * FROM `dede_myad` WHERE aid='3' LIMIT 0,1;</font>
Time2014-06-14 10:11:33
*/
?>
<?php  exit();
/*
Page: /index.php?upcache=1
Error: Unknown column 'addf.flash' in 'field list' <br />Error sql: <font color='red'>SELECT arc.*,tp.typedir,tp.typename,tp.corank,tp.isdefault,tp.defaultname,tp.namerule,
        tp.namerule2,tp.ispart,tp.moresite,tp.siteurl,tp.sitepath
        ,addf.flash
        FROM `dede_archives` arc LEFT JOIN `dede_arctype` tp on arc.typeid=tp.id
         LEFT JOIN `dede_addonarticle` addf ON addf.aid = arc.id 
         WHERE  FIND_IN_SET('f', arc.flag)>0  And  arc.channel = '1'  And  arc.arcrank > -1    ORDER BY arc.sortrank desc  LIMIT 0,6 </font>
Time2015-05-02 19:17:14
*/
?>
<?php  exit();
/*
Page: /index.php?upcache=1
Error: Unknown column 'addf.flash' in 'field list' <br />Error sql: <font color='red'>SELECT arc.*,tp.typedir,tp.typename,tp.corank,tp.isdefault,tp.defaultname,tp.namerule,
        tp.namerule2,tp.ispart,tp.moresite,tp.siteurl,tp.sitepath
        ,addf.flash
        FROM `dede_archives` arc LEFT JOIN `dede_arctype` tp on arc.typeid=tp.id
         LEFT JOIN `dede_addonarticle` addf ON addf.aid = arc.id 
         WHERE  FIND_IN_SET('f', arc.flag)>0  And  arc.channel = '1'  And  arc.arcrank > -1    ORDER BY arc.sortrank desc  LIMIT 0,6 </font>
Time2015-05-02 19:17:14
*/
?>
<?php  exit();
/*
Page: /dede/makehtml_homepage.php
Error: Unknown column 'addf.flash' in 'field list' <br />Error sql: <font color='red'>SELECT arc.*,tp.typedir,tp.typename,tp.corank,tp.isdefault,tp.defaultname,tp.namerule,
        tp.namerule2,tp.ispart,tp.moresite,tp.siteurl,tp.sitepath
        ,addf.flash
        FROM `dede_archives` arc LEFT JOIN `dede_arctype` tp on arc.typeid=tp.id
         LEFT JOIN `dede_addonarticle` addf ON addf.aid = arc.id 
         WHERE  FIND_IN_SET('f', arc.flag)>0  And  arc.channel = '1'  And  arc.arcrank > -1    ORDER BY arc.sortrank desc  LIMIT 0,6 </font>
Time2015-05-02 19:22:29
*/
?>
<?php  exit();
/*
Page: /dede/makehtml_homepage.php
Error: Unknown column 'addf.flash' in 'field list' <br />Error sql: <font color='red'>SELECT arc.*,tp.typedir,tp.typename,tp.corank,tp.isdefault,tp.defaultname,tp.namerule,
        tp.namerule2,tp.ispart,tp.moresite,tp.siteurl,tp.sitepath
        ,addf.flash
        FROM `dede_archives` arc LEFT JOIN `dede_arctype` tp on arc.typeid=tp.id
         LEFT JOIN `dede_addonarticle` addf ON addf.aid = arc.id 
         WHERE  FIND_IN_SET('f', arc.flag)>0  And  arc.channel = '1'  And  arc.arcrank > -1    ORDER BY arc.sortrank desc  LIMIT 0,6 </font>
Time2015-05-02 19:22:29
*/
?>
<?php  exit();
/*
Page: /index.php?upcache=1
Error: Unknown column 'addf.flash' in 'field list' <br />Error sql: <font color='red'>SELECT arc.*,tp.typedir,tp.typename,tp.corank,tp.isdefault,tp.defaultname,tp.namerule,
        tp.namerule2,tp.ispart,tp.moresite,tp.siteurl,tp.sitepath
        ,addf.flash
        FROM `dede_archives` arc LEFT JOIN `dede_arctype` tp on arc.typeid=tp.id
         LEFT JOIN `dede_addonarticle` addf ON addf.aid = arc.id 
         WHERE  FIND_IN_SET('f', arc.flag)>0  And  arc.channel = '1'  And  arc.arcrank > -1    ORDER BY arc.sortrank desc  LIMIT 0,6 </font>
Time2015-05-02 19:22:33
*/
?>
<?php  exit();
/*
Page: /index.php?upcache=1
Error: Unknown column 'addf.flash' in 'field list' <br />Error sql: <font color='red'>SELECT arc.*,tp.typedir,tp.typename,tp.corank,tp.isdefault,tp.defaultname,tp.namerule,
        tp.namerule2,tp.ispart,tp.moresite,tp.siteurl,tp.sitepath
        ,addf.flash
        FROM `dede_archives` arc LEFT JOIN `dede_arctype` tp on arc.typeid=tp.id
         LEFT JOIN `dede_addonarticle` addf ON addf.aid = arc.id 
         WHERE  FIND_IN_SET('f', arc.flag)>0  And  arc.channel = '1'  And  arc.arcrank > -1    ORDER BY arc.sortrank desc  LIMIT 0,6 </font>
Time2015-05-02 19:22:33
*/
?>
<?php  exit();
/*
Page: /index.php?upcache=1
Error: Unknown column 'addf.flash' in 'field list' <br />Error sql: <font color='red'>SELECT arc.*,tp.typedir,tp.typename,tp.corank,tp.isdefault,tp.defaultname,tp.namerule,
        tp.namerule2,tp.ispart,tp.moresite,tp.siteurl,tp.sitepath
        ,addf.flash
        FROM `dede_archives` arc LEFT JOIN `dede_arctype` tp on arc.typeid=tp.id
         LEFT JOIN `dede_addonarticle` addf ON addf.aid = arc.id 
         WHERE  FIND_IN_SET('f', arc.flag)>0  And  arc.channel = '1'  And  arc.arcrank > -1    ORDER BY arc.sortrank desc  LIMIT 0,6 </font>
Time2015-05-02 19:25:04
*/
?>
<?php  exit();
/*
Page: /index.php?upcache=1
Error: Unknown column 'addf.flash' in 'field list' <br />Error sql: <font color='red'>SELECT arc.*,tp.typedir,tp.typename,tp.corank,tp.isdefault,tp.defaultname,tp.namerule,
        tp.namerule2,tp.ispart,tp.moresite,tp.siteurl,tp.sitepath
        ,addf.flash
        FROM `dede_archives` arc LEFT JOIN `dede_arctype` tp on arc.typeid=tp.id
         LEFT JOIN `dede_addonarticle` addf ON addf.aid = arc.id 
         WHERE  FIND_IN_SET('f', arc.flag)>0  And  arc.channel = '1'  And  arc.arcrank > -1    ORDER BY arc.sortrank desc  LIMIT 0,6 </font>
Time2015-05-02 19:25:04
*/
?>
<?php  exit();
/*
Page: /dede/makehtml_homepage.php
Error: Unknown column 'addf.flash' in 'field list' <br />Error sql: <font color='red'>SELECT arc.*,tp.typedir,tp.typename,tp.corank,tp.isdefault,tp.defaultname,tp.namerule,
        tp.namerule2,tp.ispart,tp.moresite,tp.siteurl,tp.sitepath
        ,addf.flash
        FROM `dede_archives` arc LEFT JOIN `dede_arctype` tp on arc.typeid=tp.id
         LEFT JOIN `dede_addonarticle` addf ON addf.aid = arc.id 
         WHERE  FIND_IN_SET('f', arc.flag)>0  And  arc.channel = '1'  And  arc.arcrank > -1    ORDER BY arc.sortrank desc  LIMIT 0,6 </font>
Time2015-05-02 19:25:44
*/
?>
<?php  exit();
/*
Page: /dede/makehtml_homepage.php
Error: Unknown column 'addf.flash' in 'field list' <br />Error sql: <font color='red'>SELECT arc.*,tp.typedir,tp.typename,tp.corank,tp.isdefault,tp.defaultname,tp.namerule,
        tp.namerule2,tp.ispart,tp.moresite,tp.siteurl,tp.sitepath
        ,addf.flash
        FROM `dede_archives` arc LEFT JOIN `dede_arctype` tp on arc.typeid=tp.id
         LEFT JOIN `dede_addonarticle` addf ON addf.aid = arc.id 
         WHERE  FIND_IN_SET('f', arc.flag)>0  And  arc.channel = '1'  And  arc.arcrank > -1    ORDER BY arc.sortrank desc  LIMIT 0,6 </font>
Time2015-05-02 19:25:44
*/
?>
<?php  exit();
/*
Page: /index.php?upcache=1
Error: Unknown column 'addf.flash' in 'field list' <br />Error sql: <font color='red'>SELECT arc.*,tp.typedir,tp.typename,tp.corank,tp.isdefault,tp.defaultname,tp.namerule,
        tp.namerule2,tp.ispart,tp.moresite,tp.siteurl,tp.sitepath
        ,addf.flash
        FROM `dede_archives` arc LEFT JOIN `dede_arctype` tp on arc.typeid=tp.id
         LEFT JOIN `dede_addonarticle` addf ON addf.aid = arc.id 
         WHERE  FIND_IN_SET('f', arc.flag)>0  And  arc.channel = '1'  And  arc.arcrank > -1    ORDER BY arc.sortrank desc  LIMIT 0,6 </font>
Time2015-05-02 19:25:49
*/
?>
<?php  exit();
/*
Page: /index.php?upcache=1
Error: Unknown column 'addf.flash' in 'field list' <br />Error sql: <font color='red'>SELECT arc.*,tp.typedir,tp.typename,tp.corank,tp.isdefault,tp.defaultname,tp.namerule,
        tp.namerule2,tp.ispart,tp.moresite,tp.siteurl,tp.sitepath
        ,addf.flash
        FROM `dede_archives` arc LEFT JOIN `dede_arctype` tp on arc.typeid=tp.id
         LEFT JOIN `dede_addonarticle` addf ON addf.aid = arc.id 
         WHERE  FIND_IN_SET('f', arc.flag)>0  And  arc.channel = '1'  And  arc.arcrank > -1    ORDER BY arc.sortrank desc  LIMIT 0,6 </font>
Time2015-05-02 19:25:49
*/
?>
<?php  exit();
/*
Page: /index.php?upcache=1
Error: Unknown column 'addf.flash' in 'field list' <br />Error sql: <font color='red'>SELECT arc.*,tp.typedir,tp.typename,tp.corank,tp.isdefault,tp.defaultname,tp.namerule,
        tp.namerule2,tp.ispart,tp.moresite,tp.siteurl,tp.sitepath
        ,addf.flash
        FROM `dede_archives` arc LEFT JOIN `dede_arctype` tp on arc.typeid=tp.id
         LEFT JOIN `dede_addonarticle` addf ON addf.aid = arc.id 
         WHERE  FIND_IN_SET('f', arc.flag)>0  And  arc.channel = '1'  And  arc.arcrank > -1    ORDER BY arc.sortrank desc  LIMIT 0,6 </font>
Time2015-05-02 19:26:48
*/
?>
<?php  exit();
/*
Page: /index.php?upcache=1
Error: Unknown column 'addf.flash' in 'field list' <br />Error sql: <font color='red'>SELECT arc.*,tp.typedir,tp.typename,tp.corank,tp.isdefault,tp.defaultname,tp.namerule,
        tp.namerule2,tp.ispart,tp.moresite,tp.siteurl,tp.sitepath
        ,addf.flash
        FROM `dede_archives` arc LEFT JOIN `dede_arctype` tp on arc.typeid=tp.id
         LEFT JOIN `dede_addonarticle` addf ON addf.aid = arc.id 
         WHERE  FIND_IN_SET('f', arc.flag)>0  And  arc.channel = '1'  And  arc.arcrank > -1    ORDER BY arc.sortrank desc  LIMIT 0,6 </font>
Time2015-05-02 19:26:48
*/
?>
<?php  exit();
/*
Page: /index.php?upcache=1
Error: Unknown column 'addf.flash' in 'field list' <br />Error sql: <font color='red'>SELECT arc.*,tp.typedir,tp.typename,tp.corank,tp.isdefault,tp.defaultname,tp.namerule,
        tp.namerule2,tp.ispart,tp.moresite,tp.siteurl,tp.sitepath
        ,addf.flash
        FROM `dede_archives` arc LEFT JOIN `dede_arctype` tp on arc.typeid=tp.id
         LEFT JOIN `dede_addonarticle` addf ON addf.aid = arc.id 
         WHERE  FIND_IN_SET('f', arc.flag)>0  And  arc.channel = '1'  And  arc.arcrank > -1    ORDER BY arc.sortrank desc  LIMIT 0,6 </font>
Time2015-05-02 19:27:23
*/
?>
<?php  exit();
/*
Page: /index.php?upcache=1
Error: Unknown column 'addf.flash' in 'field list' <br />Error sql: <font color='red'>SELECT arc.*,tp.typedir,tp.typename,tp.corank,tp.isdefault,tp.defaultname,tp.namerule,
        tp.namerule2,tp.ispart,tp.moresite,tp.siteurl,tp.sitepath
        ,addf.flash
        FROM `dede_archives` arc LEFT JOIN `dede_arctype` tp on arc.typeid=tp.id
         LEFT JOIN `dede_addonarticle` addf ON addf.aid = arc.id 
         WHERE  FIND_IN_SET('f', arc.flag)>0  And  arc.channel = '1'  And  arc.arcrank > -1    ORDER BY arc.sortrank desc  LIMIT 0,6 </font>
Time2015-05-02 19:27:23
*/
?>
<?php  exit();
/*
Page: /dede/makehtml_list_action.php?typeid=0&maxpagesize=50&upnext=1
Error: Unknown column 'addf.flash' in 'field list' <br />Error sql: <font color='red'>SELECT arc.*,tp.typedir,tp.typename,tp.corank,tp.isdefault,tp.defaultname,tp.namerule,
        tp.namerule2,tp.ispart,tp.moresite,tp.siteurl,tp.sitepath
        ,addf.flash
        FROM `dede_archives` arc LEFT JOIN `dede_arctype` tp on arc.typeid=tp.id
         LEFT JOIN `dede_addonarticle` addf ON addf.aid = arc.id 
         WHERE  FIND_IN_SET('f', arc.flag)>0  And  arc.typeid IN (1,11,12,13) And  arc.channel = '1'  And  arc.arcrank > -1    ORDER BY arc.sortrank desc  LIMIT 0,6 </font>
Time2015-05-02 19:49:34
*/
?>
<?php  exit();
/*
Page: /dede/makehtml_list_action.php?gotype=&uppage=0&maxpagesize=50&typeid=0&pageno=1&isremote=0&serviterm=
Error: Unknown column 'addf.flash' in 'field list' <br />Error sql: <font color='red'>SELECT arc.*,tp.typedir,tp.typename,tp.corank,tp.isdefault,tp.defaultname,tp.namerule,
        tp.namerule2,tp.ispart,tp.moresite,tp.siteurl,tp.sitepath
        ,addf.flash
        FROM `dede_archives` arc LEFT JOIN `dede_arctype` tp on arc.typeid=tp.id
         LEFT JOIN `dede_addonarticle` addf ON addf.aid = arc.id 
         WHERE  FIND_IN_SET('f', arc.flag)>0  And  arc.typeid IN (2,14,15,16,17) And  arc.channel = '1'  And  arc.arcrank > -1    ORDER BY arc.sortrank desc  LIMIT 0,6 </font>
Time2015-05-02 19:49:35
*/
?>
<?php  exit();
/*
Page: /dede/makehtml_list_action.php?gotype=&uppage=0&maxpagesize=50&typeid=0&pageno=2&isremote=0&serviterm=
Error: Unknown column 'addf.flash' in 'field list' <br />Error sql: <font color='red'>SELECT arc.*,tp.typedir,tp.typename,tp.corank,tp.isdefault,tp.defaultname,tp.namerule,
        tp.namerule2,tp.ispart,tp.moresite,tp.siteurl,tp.sitepath
        ,addf.flash
        FROM `dede_archives` arc LEFT JOIN `dede_arctype` tp on arc.typeid=tp.id
         LEFT JOIN `dede_addonarticle` addf ON addf.aid = arc.id 
         WHERE  FIND_IN_SET('f', arc.flag)>0  And  arc.typeid IN (3,18,19) And  arc.channel = '1'  And  arc.arcrank > -1    ORDER BY arc.sortrank desc  LIMIT 0,6 </font>
Time2015-05-02 19:49:36
*/
?>
<?php  exit();
/*
Page: /dede/makehtml_list_action.php?gotype=&uppage=0&maxpagesize=50&typeid=0&pageno=3&isremote=0&serviterm=
Error: Unknown column 'addf.flash' in 'field list' <br />Error sql: <font color='red'>SELECT arc.*,tp.typedir,tp.typename,tp.corank,tp.isdefault,tp.defaultname,tp.namerule,
        tp.namerule2,tp.ispart,tp.moresite,tp.siteurl,tp.sitepath
        ,addf.flash
        FROM `dede_archives` arc LEFT JOIN `dede_arctype` tp on arc.typeid=tp.id
         LEFT JOIN `dede_addonarticle` addf ON addf.aid = arc.id 
         WHERE  FIND_IN_SET('f', arc.flag)>0  And  arc.typeid IN (4,5,6) And  arc.channel = '1'  And  arc.arcrank > -1    ORDER BY arc.sortrank desc  LIMIT 0,6 </font>
Time2015-05-02 19:49:36
*/
?>
<?php  exit();
/*
Page: /dede/makehtml_list_action.php?gotype=&uppage=0&maxpagesize=50&typeid=0&pageno=4&isremote=0&serviterm=
Error: Unknown column 'addf.flash' in 'field list' <br />Error sql: <font color='red'>SELECT arc.*,tp.typedir,tp.typename,tp.corank,tp.isdefault,tp.defaultname,tp.namerule,
        tp.namerule2,tp.ispart,tp.moresite,tp.siteurl,tp.sitepath
        ,addf.flash
        FROM `dede_archives` arc LEFT JOIN `dede_arctype` tp on arc.typeid=tp.id
         LEFT JOIN `dede_addonarticle` addf ON addf.aid = arc.id 
         WHERE  FIND_IN_SET('f', arc.flag)>0  And  arc.typeid IN (5) And  arc.channel = '1'  And  arc.arcrank > -1    ORDER BY arc.sortrank desc  LIMIT 0,6 </font>
Time2015-05-02 19:49:37
*/
?>
<?php  exit();
/*
Page: /dede/makehtml_list_action.php?gotype=&uppage=0&maxpagesize=50&typeid=0&pageno=5&isremote=0&serviterm=
Error: Unknown column 'addf.flash' in 'field list' <br />Error sql: <font color='red'>SELECT arc.*,tp.typedir,tp.typename,tp.corank,tp.isdefault,tp.defaultname,tp.namerule,
        tp.namerule2,tp.ispart,tp.moresite,tp.siteurl,tp.sitepath
        ,addf.flash
        FROM `dede_archives` arc LEFT JOIN `dede_arctype` tp on arc.typeid=tp.id
         LEFT JOIN `dede_addonarticle` addf ON addf.aid = arc.id 
         WHERE  FIND_IN_SET('f', arc.flag)>0  And  arc.typeid IN (6) And  arc.channel = '1'  And  arc.arcrank > -1    ORDER BY arc.sortrank desc  LIMIT 0,6 </font>
Time2015-05-02 19:49:37
*/
?>
<?php  exit();
/*
Page: /tags.php?/%B0%A2%C0%EF%B0%CD%B0%CD/
Error: Unknown column 'addf.flash' in 'field list' <br />Error sql: <font color='red'>SELECT arc.*,tp.typedir,tp.typename,tp.corank,tp.isdefault,tp.defaultname,tp.namerule,
        tp.namerule2,tp.ispart,tp.moresite,tp.siteurl,tp.sitepath
        ,addf.flash
        FROM `dede_archives` arc LEFT JOIN `dede_arctype` tp on arc.typeid=tp.id
         LEFT JOIN `dede_addonarticle` addf ON addf.aid = arc.id 
         WHERE  FIND_IN_SET('f', arc.flag)>0  And  arc.channel = '1'  And  arc.arcrank > -1    ORDER BY arc.sortrank desc  LIMIT 0,6 </font>
Time2015-05-02 20:57:27
*/
?>
<?php  exit();
/*
Page: /dede/login.php
Error: 无法使用数据库
Time2018-01-04 15:10:59
*/
?>
